// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: errorx.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domain is for grouping reasons
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Error is optional, if passed in, it will append to error message
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Reason is the key to get error message template
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Args is the replacer for error message template
	Args          []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_errorx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_errorx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_errorx_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ErrorInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorInfo) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ErrorInfo) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_errorx_proto protoreflect.FileDescriptor

const file_errorx_proto_rawDesc = "" +
	"\n" +
	"\ferrorx.proto\x12\x05errpb\"e\n" +
	"\tErrorInfo\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04argsB-Z+github.com/ggsrc/galaxy-errors/proto;errorsb\x06proto3"

var (
	file_errorx_proto_rawDescOnce sync.Once
	file_errorx_proto_rawDescData []byte
)

func file_errorx_proto_rawDescGZIP() []byte {
	file_errorx_proto_rawDescOnce.Do(func() {
		file_errorx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorx_proto_rawDesc), len(file_errorx_proto_rawDesc)))
	})
	return file_errorx_proto_rawDescData
}

var file_errorx_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errorx_proto_goTypes = []any{
	(*ErrorInfo)(nil), // 0: errpb.ErrorInfo
}
var file_errorx_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errorx_proto_init() }
func file_errorx_proto_init() {
	if File_errorx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorx_proto_rawDesc), len(file_errorx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorx_proto_goTypes,
		DependencyIndexes: file_errorx_proto_depIdxs,
		MessageInfos:      file_errorx_proto_msgTypes,
	}.Build()
	File_errorx_proto = out.File
	file_errorx_proto_goTypes = nil
	file_errorx_proto_depIdxs = nil
}
